In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Binarizer

# Create a sample DataFrame
data = {
    'Score': np.random.randint(30, 100, 20),
    'Age': np.random.randint(18, 70, 20),
    'Income': np.random.randint(20000, 100000, 20)
}
df = pd.DataFrame(data)

print("Original DataFrame:")
display(df.head())

Original DataFrame:

   Score  Age  Income
0     49   39   95356
1     34   43   61393
2     67   68   75023
3     30   34   31004
4     72   22   35324

In [2]:
# Binning 'Score' into 4 equal-width bins
df['Score_Binned_Equal_Width'] = pd.cut(df['Score'], bins=4, labels=['Poor', 'Fair', 'Good', 'Excellent'])

# Binning 'Age' into 3 equal-frequency (quantiles) bins
df['Age_Binned_Equal_Frequency'] = pd.qcut(df['Age'], q=3, labels=['Young', 'Middle-aged', 'Senior'])

print("DataFrame after Binning:")
display(df[['Score', 'Score_Binned_Equal_Width', 'Age', 'Age_Binned_Equal_Frequency']].head())

DataFrame after Binning:

   Score Score_Binned_Equal_Width  Age Age_Binned_Equal_Frequency
0     49                     Fair   39                      Young
1     34                     Poor   43                Middle-aged
2     67                     Good   68                     Senior
3     30                     Poor   34                      Young
4     72                     Good   22                      Young

In [3]:
# Binarization using pandas.cut for 'Income' (e.g., above/below 50000)
df['Income_Binarized_Pandas'] = pd.cut(df['Income'], bins=[0, 50000, np.inf], labels=[0, 1], right=False)

# Binarization using sklearn.preprocessing.Binarizer for 'Score'
# Let's binarize 'Score' where anything >= 70 is 'high' (1), else 'low' (0)
binarizer = Binarizer(threshold=70)
df['Score_Binarized_Sklearn'] = binarizer.fit_transform(df[['Score']])

print("DataFrame after Binarization:")
display(df[['Income', 'Income_Binarized_Pandas', 'Score', 'Score_Binarized_Sklearn']].head())

DataFrame after Binarization:

   Income Income_Binarized_Pandas  Score  Score_Binarized_Sklearn
0   95356                       1     49                        0
1   61393                       1     34                        0
2   75023                       1     67                        0
3   31004                       0     30                        0
4   35324                       0     72                        1